### ISSUE TITLE
Is normal not faction appears

### ISSUE THREAD

**Issue by Willtom999** [WalnutDev27/PureChat-WalnutMod#1]
![46E516D4-E314-446A-90DA-693038D1E0AF](https://user-images.githubusercontent.com/83521998/126877462-92312e99-4c19-4182-9d4d-47ab68c9cd02.png)

**Comment by Willtom999** [comment]
Because is create fac is not appears on pseudo

**Comment by WalnutDev27** [comment]
Hi, what is the Faction plugin that you are used??

**Comment by Willtom999** [comment]
SimpleFactions

**Comment by WalnutDev27** [comment]
ok, is possible that you can placed the {faction_name} variable in the nametag section of this rank. But this bug only happened in this rank, or is in all ranks?

**Comment by Willtom999** [comment]
Ok

**Comment by Willtom999** [comment]
in the beginning

**Comment by Willtom999** [comment]
Is not walk

**Comment by Willtom999** [comment]
@WalnutDev27

**Comment by WalnutDev27** [comment]
But this in all ranks, or is only in this rank??

**Comment by Willtom999** [comment]
All

**Comment by WalnutDev27** [comment]
ok, I'll see what's happening, thanks for reporting the problem

**Comment by Willtom999** [comment]
will be settled soon?

**Comment by WalnutDev27** [comment]
yes

**Comment by Willtom999** [comment]
ok

**Comment by WalnutDev27** [comment]
Hi, can you give me the config.yml of your server, is fo see this, and if the error is because the config is bad.

**Comment by Willtom999** [comment]
Ok

**Comment by Willtom999** [comment]
chat: §9[{fac_rank}{fac_name}]&8[§4Yout§auber]&f {display_name} &c> {msg}
  §eBuilder:
    nametag: '&c[{fac_rank}{fac_name}]&8[§eBuilder]&f {display_name}'
    chat: '&c[{fac_rank}{fac_name}]&8[§eBuilder]&f {display_name} &e> {msg}'
  §bGuide:
    nametag: '&c[{fac_rank}{fac_name}]&8[§bGuide]&f {display_name}'
    chat: '&c[{fac_rank}{fac_name}]&8[§bGuide]&f {display_name} &b> {msg}'
  §aModérateur:
    nametag: '&c[{fac_rank}{fac_name}]&8[§aModérateur]&f {display_name}'
    chat: '&c[{fac_rank}{fac_name}]&8[§aModérateur]&f {display_name} &2> {msg}'
  §6Super-Modérateur:
    nametag: '&c[{fac_rank}{fac_name}]&8[§6Super-Modérateur]&f {display_name}'
    chat: '&c[{fac_rank}{fac_name}]&8[§6Super-Modérateur]&f {display_name} &6> {msg}'
  §9Responsable:
    nametag: '&c[{fac_rank}{fac_name}]&8[§9Responsable]&f {display_name}'
    chat: '&c[{fac_rank}{fac_name}]&8[§9Responsable]&f {display_name} &9> {msg}'
  §6Developper:
    nametag: '&c[{fac_rank}{fac_name}]&8[§6Developper]&f {display_name}'
    chat: '&c[{fac_rank}{fac_name}]&8[§6Developper]&f {display_name} &e> {msg}'
  §4Admin:
    nametag: '&c[{fac_rank}{fac_name}]&8[§4Admin]&f {display_name}'
    chat: '&c[{fac_rank}{fac_name}]&8[§4Admin]&f {display_name} &c> {msg}'
  §3Fondateur:
    nametag: '&c[{fac_rank}{faction_name}]&8 [§3Fondateur]&f {display_name}'
    chat: '&c[{fac_rank}{fac_name}]&8 [§3Fondateur]&f {display_name} &1> {msg}'
  Co-Fonda:
    nametag: '&8&l[Co-Fonda]&f&r {display_name}'
    chat: '&8&l[Co-Fonda]&f&r {display_name} &7> {msg}'
...

**Comment by Willtom999** [comment]
worlds: []
  OP:
    chat: '&a[OP] &5{fac_rank}{fac_name}&b {prefix}{display_name}{suffix} &c>&6> &f{msg}'
    nametag: '&a[OP] &c{fac_rank}{fac_name} &b{display_name}'
    worlds: []
  Fondateur:
    nametag: '&8&l[Fondateur]&f&r {display_name}'
    chat: '&8&l[Fondateur]&f&r {display_name} &7> {msg}'
  §5Minecraftien:
    nametag: '§5[{fac_rank}{fac_name}]§8[§5Minecraftien]&f {display_name}'
    chat: '§5{fac_rank}{fac_name}&8[§5Minecraftien]&f {display_name} &3> {msg}'
  §aEmeraude:
    nametag: §2[{fac_rank}{fac_name}]&8[§aEmeraude]&f {display_name}
    chat: §2[{fac_rank}{fac_name}]&8[§aEmeraude]&f {display_name} &a> {msg}
  §cRuby:
    nametag: §4[{fac_rank}{fac_name}]&8[§cRuby]&f {display_name}
    chat: §4[{fac_rank}{fac_name}]&8[§cRuby]&f {display_name} &4> {msg}
  §1Saphire:
    nametag: §1[{fac_rank}{fac_name}]&8[§1Saphire]&f {display_name}
    chat: §1[{fac_rank}{fac_name}&8[§1Saphire]&f {display_name} &9> {msg}
  §4Yout§auber:
    nametag: §9[{fac_rank}{fac_name}]&8[§4Yout§auber]&f {display_name}

**Comment by Willtom999** [comment]
# Set default factions plugin for PureChat
default-factions-plugin: SimpleFactions

# Enable this if you want to use per-world chat formats / per-world nametags for players
# - true / false
enable-multiworld-chat: false

# Please check if you have all PurePerms groups in your server here

# &0: Black, &1: Dark Blue, &2: Dark Green, &3: Dark Aqua, &4: Dark Red, &5: Dark Purple, &6: Gold, &7: Gray, &8: Dark Gray, &9: Blue
# &a: Green, &b: Aqua, &c: Red, &d: Light Purple, &e: Yellow, &f: White
# &k: Obfuscated, &l: Bold, &m: Strikethrough, &n: Underline, &o: Italic, &r: Reset

# Available PureChat tags: {display_name}, {msg}, {fac_name}, {fac_rank}, {prefix}, {suffix}, {world}, {health}, {ping}, {food}, {x}, {y}, {z}
